// src/routes/blog/+page.svelte
<script lang="ts">
	import Hero from '#lib/components/Hero.svelte';
	import PostCard from '#lib/components/PostCard.svelte';
	import Seo from '#lib/components/Seo.svelte';
	import { LINKS } from '#lib/site.js';
	import { breadcrumbs } from '#lib/structured-data.js';
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();

	const DESCRIPTION =
		"Hurc's Corner. The Golden Hurriblog. Whatever you want to call it, we'll use this to dive deeper into stats, explore TU history, and more.";
</script>

<Seo
	title="Blog"
	description={DESCRIPTION}
	jsonLd={breadcrumbs([
		{ name: 'Home', path: '/' },
		{ name: 'Blog', path: '/blog/' }
	])}
/>

<Hero title="Our Blog">
	{#snippet lead()}
		{DESCRIPTION}
	{/snippet}

	<p>
		You can <a href="/tags/" class="text-primary-hover">browse posts by tag</a>, or view all of our
		posts below.
	</p>
</Hero>

<section aria-labelledby="all-posts" class="mx-auto max-w-content px-4 pb-12 sm:px-8">
	<h2 id="all-posts" class="mb-2 text-h4">All Posts</h2>
	<p class="font-bold">
		This blog has been discontinued. We're primarily writing over on our
		<a href={LINKS.patreon} target="_blank" rel="noopener noreferrer">Patreon</a> now. Check it out!
	</p>
	<hr />

	<ul class="space-y-4">
		{#each data.posts as post (post.slug)}
			<li><PostCard {post} /></li>
		{/each}
	</ul>
</section>

// src/pages/blog.jsx
import React from 'react'
import NavigationBar from '../components/NavigationBar'
import BlogJumbotron from '../components/BlogJumbotron'
import Container from 'react-bootstrap/Container'
import Seo from '../components/seo'
import { graphql, Link } from 'gatsby'

const BlogLayout = ({data}) => {
    const { edges } = data.allMarkdownRemark
    return (
      <div>
        <NavigationBar />
        <BlogJumbotron />

        <div
          style={{
            marginLeft: '30px',
            marginRight: '30px',
            marginBottom: '30px',
          }}
        >

          <div style={{display: 'flex', alignItems: 'center'}}>
            <Container className='blogedge'>
              <h4>All Posts</h4>
              <p style={{ fontWeight:"bold" }}>This blog has been discontinued. We're primarily writing over on our <a href="https://patreon.com/thegoldenhurricast">Patreon</a> now. Check it out!</p>
              <hr style={{width: '100%'}} />
            </Container>
          </div>

          {edges.map(edge => {
            const { frontmatter } = edge.node
            return (
              <div key={frontmatter.path} style={{display: 'flex', alignItems: 'center'}}>
                <Container className='blogedge'>
                    <Link
                      style={{
                        textDecoration: 'none'
                      }}
                      
                      to={`${frontmatter.path}`}
                    >
                      <div className='floating_still_blog'>
                        <p className='blog_title'>
                          {frontmatter.title}
                        </p>

                        <p className='blog_bylines'>
                          {frontmatter.date}
                        </p>
                        <p className='blog_bylines'>
                          {frontmatter.excerpt}
                        </p>
                      </div>
                    </Link>
                </Container>
              </div>
            )
          })}
        </div>
      </div>
    )
}

export const query = graphql`
         query BlogQuery {
           allMarkdownRemark(
             sort: { frontmatter: { sortDate: DESC } }
           ) {
             edges {
               node {
                 frontmatter {
                   title
                   path
                   date
                   sortDate
                   excerpt
                 }
               }
             }
           }
         }
       `

export default BlogLayout

export const Head = ({ location }) => {
  return (
    <>
      <Seo
        title={'The Golden Hurricast – Blog'}
        description={"Hurc's Corner. The Golden Hurriblog. Whatever you want to call it, we'll use this to dive deeper into stats, explore TU history, and more"}
        image={'/logo-white.jpg'}
        pathname={location.pathname}
      />
      <meta charSet='utf-8' />
      <title>TGH | Blog</title>
    </>
  )
}
